name: flores_jrs
description: App oficial del club Flores Juniors
publish_to: 'none'

version: 2.0.2+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.1.0
  shared_preferences: ^2.2.2
  local_auth: ^2.3.0
  local_auth_android: ^1.0.49
  firebase_core: ^3.15.2
  firebase_core_web: ^2.24.1
  firebase_messaging: ^15.2.9
  firebase_messaging_web: ^3.10.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/flores_jrs_logo.png
    - assets/images/icon.png # <- icono del launcher

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf

flutter_icons:
  android: true
  ios: false
  image_path: "assets/images/icon.png"

